CREATE PROCEDURE [dbo].[Populate_Person_ContactType]
AS
BEGIN
/*
	Table's data:    [Person].[ContactType]
	Data Source:     [DEV19].[AdventureWorks2014]
	Created on:      18/10/2019 15:02:26
	Scripted by:     DEV19\Administrator
	Generated by     Data Script Writer - ver. 2.0.0.0
*/
PRINT 'Populating data into [Person].[ContactType]';

IF OBJECT_ID('tempdb.dbo.#Person_ContactType') IS NOT NULL DROP TABLE #Person_ContactType;
SELECT * INTO #Person_ContactType FROM [Person].[ContactType] WHERE 0=1;

INSERT INTO #Person_ContactType 
 ([ContactTypeID], [Name], [ModifiedDate])
SELECT CAST([ContactTypeID] AS int) AS [ContactTypeID], [Name], [ModifiedDate] FROM 
(VALUES
	  (1,	'Accounting Manager',	'20080430 00:00:00.000')
	, (2,	'Assistant Sales Agent',	'20080430 00:00:00.000')
	, (3,	'Assistant Sales Representative',	'20080430 00:00:00.000')
	, (4,	'Coordinator Foreign Markets',	'20080430 00:00:00.000')
	, (5,	'Export Administrator',	'20080430 00:00:00.000')
	, (6,	'International Marketing Manager',	'20080430 00:00:00.000')
	, (7,	'Marketing Assistant',	'20080430 00:00:00.000')
	, (8,	'Marketing Manager',	'20080430 00:00:00.000')
	, (9,	'Marketing Representative',	'20080430 00:00:00.000')
	, (10,	'Order Administrator',	'20080430 00:00:00.000')
	, (11,	'Owner',	'20080430 00:00:00.000')
	, (12,	'Owner/Marketing Assistant',	'20080430 00:00:00.000')
	, (13,	'Product Manager',	'20080430 00:00:00.000')
	, (14,	'Purchasing Agent',	'20080430 00:00:00.000')
	, (15,	'Purchasing Manager',	'20080430 00:00:00.000')
	, (16,	'Regional Account Representative',	'20080430 00:00:00.000')
	, (17,	'Sales Agent',	'20080430 00:00:00.000')
	, (18,	'Sales Associate',	'20080430 00:00:00.000')
	, (19,	'Sales Manager',	'20080430 00:00:00.000')
	, (20,	'Sales Representative',	'20080430 00:00:00.000')
) as v ([ContactTypeID], [Name], [ModifiedDate]);



WITH cte_data as (SELECT CAST([ContactTypeID] AS int) AS [ContactTypeID], [Name], [ModifiedDate] FROM [#Person_ContactType])
MERGE [Person].[ContactType] as t
USING cte_data as s
	ON t.[ContactTypeID] = s.[ContactTypeID]
WHEN NOT MATCHED BY target THEN
	INSERT ([ContactTypeID], [Name], [ModifiedDate])
	VALUES (s.[ContactTypeID], s.[Name], s.[ModifiedDate])
WHEN MATCHED THEN 
	UPDATE SET 
	[Name] = s.[Name], [ModifiedDate] = s.[ModifiedDate]
WHEN NOT MATCHED BY source THEN
	DELETE
;

DROP TABLE #Person_ContactType;

-- End data of table: [Person].[ContactType] --
END
GO
