CREATE PROCEDURE [dbo].[Populate_Person_AddressType]
AS
BEGIN
/*
	Table's data:    [Person].[AddressType]
	Data Source:     [DEV19].[AdventureWorks2014]
	Created on:      18/10/2019 15:00:40
	Scripted by:     DEV19\Administrator
	Generated by     Data Script Writer - ver. 2.0.0.0
*/
PRINT 'Populating data into [Person].[AddressType]';

IF NOT EXISTS (SELECT TOP (1) * FROM [Person].[AddressType])
BEGIN

	;WITH cte_data
	as (SELECT [AddressTypeID], [Name], [rowguid], [ModifiedDate] FROM 
	(VALUES
	  (1,	'Billing',	'b84f78b1-4efe-4a0e-8cb7-70e9f112f886',	'20080430 00:00:00.000')
	, (2,	'Home',	'41bc2ff6-f0fc-475f-8eb9-cec0805aa0f2',	'20080430 00:00:00.000')
	, (3,	'Main Office',	'8eeec28c-07a2-4fb9-ad0a-42d4a0bbc575',	'20080430 00:00:00.000')
	, (4,	'Primary',	'24cb3088-4345-47c4-86c5-17b535133d1e',	'20080430 00:00:00.000')
	, (5,	'Shipping',	'b29da3f8-19a3-47da-9daa-15c84f4a83a5',	'20080430 00:00:00.000')
	, (6,	'Archive',	'a67f238a-5ba2-444b-966c-0467ed9c427f',	'20080430 00:00:00.000')
	) as v ([AddressTypeID], [Name], [rowguid], [ModifiedDate])
)
	INSERT INTO [Person].[AddressType]
	([AddressTypeID], [Name], [rowguid], [ModifiedDate])
	SELECT [AddressTypeID], [Name], [rowguid], [ModifiedDate]
	FROM cte_data;

END

-- End data of table: [Person].[AddressType] --
END
GO
