CREATE PROCEDURE [data].[Populate_Person_PhoneNumberType]
AS
BEGIN
/*
	Table's data:    [Person].[PhoneNumberType]
	Data Source:     [DEV19].[AdventureWorks2014]
	Created on:      18/10/2019 15:07:03
	Scripted by:     DEV19\Administrator
	Generated by     Data Script Writer - ver. 2.0.0.0
*/
PRINT 'Populating data into [Person].[PhoneNumberType]';

IF NOT EXISTS (SELECT TOP (1) * FROM [Person].[PhoneNumberType])
BEGIN

	;WITH cte_data
	as (SELECT [PhoneNumberTypeID], [Name], [ModifiedDate] FROM 
	(VALUES
	  (1,	'Cell',	'20171213 13:19:22.273')
	, (2,	'Home',	'20171213 13:19:22.273')
	, (3,	'Work',	'20171213 13:19:22.273')
	) as v ([PhoneNumberTypeID], [Name], [ModifiedDate])
)
	INSERT INTO [Person].[PhoneNumberType]
	([PhoneNumberTypeID], [Name], [ModifiedDate])
	SELECT [PhoneNumberTypeID], [Name], [ModifiedDate]
	FROM cte_data;

END

-- End data of table: [Person].[PhoneNumberType] --
END
GO
